### ISSUE TITLE
Meta: add builtins

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix#1030]
Which are left:
Important:
  * [ ] #1055
  * [ ] #1034
  * [ ] #233
    Parts of implementation of it should be in #755
  * [ ] #240
  * [ ] #273
  * [ ] #162
  * [x] #128
    There is implementation of it in #755
    Ported in #1032
  * [x] Implement builtins.groubBy #1033
  * [x] Implement builtins.unsafeDiscardOutputDependency
    There is implementation of it in #755
    Ported in #1032
  * [x] Implement builtins.ceil #1031
  * [x] Implement builtins.floor #1031

Of smaller importance:
  * [ ] builtins.fetchMercurial
  * [ ] builtins.fromTOML
  
This is currently it.

**Comment by soulomoon** [comment]
> Which are left: Important:
> 
> * [ ]  [Implement builtins.path #128](https://github.com/haskell-nix/hnix/issues/128)
>   There is implementation of it in [Support uploading filtered paths to the store #755](https://github.com/haskell-nix/hnix/pull/755)
> * [ ]  [Implement builtins.fetchTarball #162](https://github.com/haskell-nix/hnix/issues/162)
> * [ ]  [Implement builtins.filterSource #233](https://github.com/haskell-nix/hnix/issues/233)
> * [ ]  [Implement builtins.storePath #240](https://github.com/haskell-nix/hnix/issues/240)
> * [ ]  [Implement builtins.builtins #273](https://github.com/haskell-nix/hnix/issues/273)
> * [ ]  Implement builtins.groubBy
> * [ ]  Implement builtins.filterSource
> * [ ]  Implement builtins.storePath
> * [ ]  Implement builtins.unsafeDiscardOutputDependency
>   There is implementation of it in [Support uploading filtered paths to the store #755](https://github.com/haskell-nix/hnix/pull/755)
> * [ ]  Implement builtins.fetchGit
> * [ ]  Implement builtins.ceil
> * [ ]  Implement builtins.floor
> 
> Of smaller importance:
> 
> * [ ]  builtins.fetchMercurial
> * [ ]  builtins.fromTOML
> 
> This is currently it.

ceil and floor should be easy, and filterSource is duplicated in the list

**Comment by Anton-Latukha** [comment]
Yes. That is why I kept them in "Important", because there is no point to postpone them.

**Comment by Anton-Latukha** [comment]
I already futurePorted `unsafeDiscardOutputDependency`, and now trying to port `path`.

**Comment by Anton-Latukha** [comment]
Also ported `path`.

**Comment by soulomoon** [comment]
I am porting `groubBy` now.  

----------------------------------

`groubBy` ported

**Comment by Anton-Latukha** [comment]
`fetchTarball` was already implemented.

**Comment by sorki** [comment]
Nix 2.6 adds another builtin - `zipAttrsWith` which is a port of nixpkgs lib version.

**Comment by Anton-Latukha** [comment]
Updated the headpost & created an according report thread for it.

Be free to add such information into the headpost, especially when those are "my" messages - I encourage correcting me or adding relevant information into messages, especially in the headposts. Also notification is not needed, GitHub provides notifications and changelogging.
