### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix#628]
`0.9.0` is out.

Currently, the main questions that I see that project has for the next release milestone are:

(I am basically rephrasing text from previous release thread, please add your ideas)

  - [x] #588 Lets free from unneeded dependencies using GHC 8.10 feature
  - [x] #592 GHC 8.10, - it already builds - so it leads https://matrix.hackage.haskell.org/#/package/hnix :1st_place_medal:. To claim the official support of GHC 8.10 - make our CI test for it. Because Nixpkgs currently 8.8.3. CI should also have classic Cabal build for us to easily detect Nixpkgs problems.
  - [ ] #618 `doCheck` all tests for HNix in Nixpkgs

Official GHC 8.10 support and having a set of proper dependencies is enough legitimacy to form the next release, by these criteria it is a minor release.

**Comment by Anton-Latukha** [comment]
In fact Nixpkgs synced-up to our needs and now CI builds GHC 8.10: https://travis-ci.org/github/haskell-nix/hnix/jobs/698345815
Wow, that escalated quickly, we can enable mandatory GHC 8.10 now.

But classic Cabal build is still a needed build to have to monitor Nixpkgs further.
In last year Nixpkgs lost in stability.

**Comment by sjakobi** [comment]
It would be nice to make a release now that `hnix` is compatible with the latest `repline`. Or are there issues or PRs that we should wait for?

* Maybe https://github.com/haskell-nix/hnix/pull/668?
* https://github.com/haskell-nix/hnix/issues/618 looks mostly blocked on Nixpkgs not using GHC 8.10 yet, so maybe it's not worth waiting for!?

**Comment by Anton-Latukha** [comment]
Yey.

It felt like infinity to me.

But you actually said this "just" 3 days ago.

Yes.
We needed #668.

Lets form a release right on this place.

I am Ok with anybody forming a release. @sorki (@jwiegley) can/should be entitled (have rights) to make a release, since in this release he shown his skills and brought the major swath of contributions. Or if he would lazily pass it to me - I can/want form it, since it would be second release ever for me, so I learn more, and also is @sjakobi wants - he can make a release, since I did the previous release.

**Comment by sjakobi** [comment]
@sorki Are you interested in preparing the release?

Otherwise I can do it, but I'd probably need you to check the changelog! :)

**Comment by sorki** [comment]
Yup! Drafted at #673

**Comment by Anton-Latukha** [comment]
Ok, since no one took responsibility to make a release, `sorki` so far probably didn't get the rights to Hackage, and we already ironed a changelog.

I would make a release then.

**Comment by Anton-Latukha** [comment]
Release made.

Docs uploaded manually.

**Comment by Anton-Latukha** [comment]
[Next release thread](https://github.com/haskell-nix/hnix/issues/675)
